# 项目基础配置
spring:
  application:
    name: game-card-sell

  # 默认激活开发环境配置
  profiles:
    active: dev

# MyBatis / MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath:mappers/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.liuao.game_card_sell.entity

# 自定义文件上传路径
file:
  upload-dir: uploads/
  access-path: /images/**