# 跨域配置
cors:
  allowed-origins: "http://localhost:5173"

# 开发环境组件配置
spring:
  # 数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/game_card_sell?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: game_user
    password: asd789*
    type: com.zaxxer.hikari.HikariDataSource

  # RabbitMQ 连接
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

 # redis 连接
  data:
    redis:
      # Redis 服务器地址
      host: localhost
      # Redis 服务器端口
      port: 6379
      # Redis 服务器连接密码（默认为空）
      # password: your_password
      # 连接池配置
      lettuce:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池中的最小空闲连接
          min-idle: 0
      # 数据库索引（默认是 0）
      database: 0
      # 连接超时时间
      timeout: 10000ms

# 日志配置
logging:
  level:
    # 业务 Mapper 调试
    com.liuao.game_card_sell.mapper: DEBUG
    # MyBatis 框架及 SQL 打印
    org.apache.ibatis: DEBUG
    java.sql.Connection: DEBUG
    java.sql.PreparedStatement: DEBUG
    # 框架运行信息
    org.mybatis.spring.SqlSessionUtils: INFO
    org.mybatis.spring.transaction.SpringManagedTransaction: INFO